# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Sun Oct 21 19:25:23 PDT 2012
#
#/ usage: jenkins:install-plugin  --name|-n <> [ --restart|-r <false>] [ --url|-u <http://updates.jenkins-ci.org>] [ --version|-v <latest>] 

# print USAGE and exit
rerun_option_usage() {
    grep '^#/ usage:' <"$0" | cut -c4- >&2
    return 2
}

# print SYNTAX and exit
rerun_option_error() {
    if [[ "$RERUN_COLOR" == "true" ]]
    then echo >&2 -e """SYNTAX: $*"""
    else echo >&2 "SYNTAX: $*" 
    fi
    exit 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_usage
}

# options: [name restart url version]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        --name|-n) rerun_option_check $# ; NAME=$2 ; shift ;;
        --restart|-r) rerun_option_check $# ; RESTART=$2 ; shift ;;
        --url|-u) rerun_option_check $# ; URL=$2 ; shift ;;
        --version|-v) rerun_option_check $# ; VERSION=$2 ; shift ;;
        # help option
        -?)
            rerun_option_usage
            exit 2
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$RESTART" ] && RESTART="false"
[ -z "$URL" ] && URL="http://updates.jenkins-ci.org"
[ -z "$VERSION" ] && VERSION="latest"
# Check required options are set
[ -z "$NAME" ] && { echo >&2 "missing required option: --name" ; return 2 ; }
# If option variables are declared exportable, export them.

#
return 0
