# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Nov 13 16:32:33 PST 2012
#
#/ usage: jenkins:install-plugin [ --restart|-r <false>] [ --jenkins-home </var/lib/jenkins>] [ --plugin-url|-p <http://updates.jenkins-ci.org>]  --plugin-name|-p <> [ --plugin-version|-p <latest>]  --jenkins-url|-j <http://localhost:8080> [ --force <false>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --restart|-r) rerun_option_check $# ; RESTART=$2 ; shift ;;
            --jenkins-home) rerun_option_check $# ; JENKINS_HOME=$2 ; shift ;;
            --plugin-url|-p) rerun_option_check $# ; PLUGIN_URL=$2 ; shift ;;
            --plugin-name|-p) rerun_option_check $# ; PLUGIN_NAME=$2 ; shift ;;
            --plugin-version|-p) rerun_option_check $# ; PLUGIN_VERSION=$2 ; shift ;;
            --jenkins-url|-j) rerun_option_check $# ; JENKINS_URL=$2 ; shift ;;
            --force) rerun_option_check $# ; FORCE=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$RESTART" ] && RESTART="false"
    [ -z "$JENKINS_HOME" ] && JENKINS_HOME="/var/lib/jenkins"
    [ -z "$PLUGIN_URL" ] && PLUGIN_URL="http://updates.jenkins-ci.org"
    [ -z "$PLUGIN_VERSION" ] && PLUGIN_VERSION="latest"
    [ -z "$JENKINS_URL" ] && JENKINS_URL="http://localhost:8080"
    [ -z "$FORCE" ] && FORCE="false"
    # Check required options are set
    [ -z "$PLUGIN_NAME" ] && { echo >&2 "missing required option: --plugin-name" ; return 2 ; }
    [ -z "$JENKINS_URL" ] && { echo >&2 "missing required option: --jenkins-url" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export JENKINS_URL
    #
    return 0
}


# Initialize the options variables to null.
RESTART=
JENKINS_HOME=
PLUGIN_URL=
PLUGIN_NAME=
PLUGIN_VERSION=
JENKINS_URL=
FORCE=


