#!/usr/bin/env bash
#
#/ command: jenkins:reload: "reload the jenkins configuration"
#
#/ usage: rerun jenkins:reload [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/reload/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/reload/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: jenkins:reload. ***"' ERR
set -o nounset -o pipefail


# ------------------------------
# Your implementation goes here.
# ------------------------------

echo reloading $JENKINS_URL

curl -s -k -f $JENKINS_URL/reload

JENKINS_HOME=/var/lib/jenkins
timeout 30 bash -c 'while [ 1 ]; do test -f ${JENKINS_HOME}/config.xml && { break; }; sleep 1; done'

exit $?

# Done
