# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Sun Oct 21 20:56:49 PDT 2012
#
#/ usage: jenkins:configure-rundeck-plugin [ --password|-p <admin>] [ --restart|-r <false>] [ --url|-u <http://localhost:4440>] [ --username|-u <admin>] 

# print USAGE and exit
rerun_option_usage() {
    grep '^#/ usage:' <"$0" | cut -c4- >&2
    return 2
}

# print SYNTAX and exit
rerun_option_error() {
    if [[ "$RERUN_COLOR" == "true" ]]
    then echo >&2 -e """SYNTAX: $*"""
    else echo >&2 "SYNTAX: $*" 
    fi
    exit 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_usage
}

# options: [password restart url username]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        --password|-p) rerun_option_check $# ; PASSWORD=$2 ; shift ;;
        --restart|-r) rerun_option_check $# ; RESTART=$2 ; shift ;;
        --url|-u) rerun_option_check $# ; URL=$2 ; shift ;;
        --username|-u) rerun_option_check $# ; USERNAME=$2 ; shift ;;
        # help option
        -?)
            rerun_option_usage
            exit 2
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$PASSWORD" ] && PASSWORD="admin"
[ -z "$RESTART" ] && RESTART="false"
[ -z "$URL" ] && URL="http://localhost:4440"
[ -z "$USERNAME" ] && USERNAME="admin"
# Check required options are set

# If option variables are declared exportable, export them.

#
return 0
