#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: jenkins:configure-rundeck-plugin: "Configure the Jenkins Rundeck plugin"
#/ usage: rerun jenkins:configure-rundeck-plugin [ --restart|-r <false>] [ --jenkins-home </var/lib/jenkins>] [ --rundeck-username|-r <admin>] [ --rundeck-password|-r <admin>] [ --rundeck-url <http://localhost:4440>] 

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh configure-rundeck-plugin || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: jenkins:configure-rundeck-plugin. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: RESTART JENKINS_HOME RUNDECK_USERNAME RUNDECK_PASSWORD RUNDECK_URL

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

sed -e "s+\${RUNDECK_URL}+${RUNDECK_URL}+" -e "s+\${RUNDECK_USERNAME}+${RUNDECK_USERNAME}+" -e "s+\${RUNDECK_PASSWORD}+${RUNDECK_PASSWORD}+" $RERUN_MODULE_DIR/templates/org.jenkinsci.plugins.rundeck.RundeckNotifier.xml | sudo -u jenkins /bin/sh -c "cat > ${JENKINS_HOME}/org.jenkinsci.plugins.rundeck.RundeckNotifier.xml"

if [[ "${RESTART}" = "true" ]]
then
  rerun jenkins:restart
fi

exit $?

# Done
