# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Mon Nov 12 12:10:57 PST 2012
#
#/ usage: jenkins:add-maven [ --maven-name|-m <maven>] [ --maven-home|-m </usr/share/maven>] [ --reload|-r <true>] [ --jenkins-url|-u <http://localhost:8080>] [ --jenkins-home|-j </var/lib/jenkins>]

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --maven-name|-m) rerun_option_check $# ; MAVEN_NAME=$2 ; shift ;;
            --maven-home|-m) rerun_option_check $# ; MAVEN_HOME=$2 ; shift ;;
            --reload|-r) rerun_option_check $# ; RELOAD=$2 ; shift ;;
            --jenkins-url|-u) rerun_option_check $# ; URL=$2 ; shift ;;
            --jenkins-home|-j) rerun_option_check $# ; JENKINS_HOME=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$MAVEN_NAME" ] && MAVEN_NAME="maven"
    [ -z "$MAVEN_HOME" ] && MAVEN_HOME="/usr/share/maven"
    [ -z "$RELOAD" ] && RELOAD="true"
    [ -z "$URL" ] && URL="http://localhost:8080"
    [ -z "$JENKINS_HOME" ] && JENKINS_HOME="/var/lib/jenkins"
    # Check required options are set

    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
MAVEN_NAME=
MAVEN_HOME=
RELOAD=
URL=
JENKINS_HOME=
URL=


