# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Nov 27 15:45:35 PST 2012
#
#/ usage: jenkins:add-maven [ --maven-name <maven>] [ --maven-home|-m </usr/share/maven>] [ --jenkins-home </var/lib/jenkins>] [ --restart|-r <false>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --maven-name) rerun_option_check $# ; MAVEN_NAME=$2 ; shift ;;
            --maven-home|-m) rerun_option_check $# ; MAVEN_HOME=$2 ; shift ;;
            --jenkins-home) rerun_option_check $# ; JENKINS_HOME=$2 ; shift ;;
            --restart|-r) rerun_option_check $# ; RESTART=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$MAVEN_NAME" ] && MAVEN_NAME="maven"
    [ -z "$MAVEN_HOME" ] && MAVEN_HOME="/usr/share/maven"
    [ -z "$JENKINS_HOME" ] && JENKINS_HOME="/var/lib/jenkins"
    [ -z "$RESTART" ] && RESTART="false"
    # Check required options are set

    # If option variables are declared exportable, export them.
    export JENKINS_HOME
    #
    return 0
}


# Initialize the options variables to null.
MAVEN_NAME=
MAVEN_HOME=
JENKINS_HOME=
RESTART=


