#!/usr/bin/env bash
#
#/ command: jenkins:add-maven: "Adds a Maven installation to the Jenkins configuration"
#
#/ usage: rerun jenkins:add-maven [ --maven-name|-m <maven>] [ --maven-home|-m </usr/share/maven>] [ --jenkins-home </var/lib/jenkins>] [ --restart <false>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: MAVEN_NAME MAVEN_HOME JENKINS_HOME RESTART

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/add-maven/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/add-maven/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: jenkins:add-maven. ***"' ERR
set -o nounset -o pipefail


# ------------------------------
# Your implementation goes here.
# ------------------------------

sed -e "s+\${MAVEN_NAME}+${MAVEN_NAME}+" -e "s+\${MAVEN_HOME}+${MAVEN_HOME}+" $RERUN_MODULE_DIR/templates/hudson.tasks.Maven.xml | sudo -u jenkins /bin/sh -c "cat > ${JENKINS_HOME}/hudson.tasks.Maven.xml"

if [[ "${RESTART}" = "true" ]]
then
  rerun jenkins:restart
fi

exit $?

# Done
