#!/usr/bin/env bash
#
#/ command: jenkins:build-now: "Perform a build of the specified job"
#
#/ usage: rerun jenkins:build-now  --jobname <> [ --jenkins-url <http://localhost:8080>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: JOBNAME JENKINS_URL

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: jenkins:build-now. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/build-now/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/build-now/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

curl -fs --data ""  "${JENKINS_URL}/job/${JOBNAME}/build"

exit $?

# Done
