#!/usr/bin/env bash
#
#/ command: jenkins:install: "Install Jenkins"
#
#/ usage: rerun jenkins:install [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/install/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/install/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: jenkins:install. ***"' ERR
set -o nounset -o pipefail


# ------------------------------
# Your implementation goes here.
# ------------------------------

if ! rpm --quiet -q jenkins
then
  sudo wget --quiet -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
  sudo rpm --quiet --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
  sudo yum --quiet -y install jenkins
fi

exit $?

# Done
