# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Mon Nov 12 11:04:31 PST 2012
#
#/ usage: jenkins:add-jdk [ --config-file|-c </var/lib/jenkins/config.xml>] [ --jdk-name|-j <java-sdk>] [ --jdk-home|-j </etc/alternatives/java_sdk>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --config-file|-c) rerun_option_check $# ; CONFIG_FILE=$2 ; shift ;;
            --jdk-name|-j) rerun_option_check $# ; JDK_NAME=$2 ; shift ;;
            --jdk-home|-j) rerun_option_check $# ; JDK_HOME=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$CONFIG_FILE" ] && CONFIG_FILE="/var/lib/jenkins/config.xml"
    [ -z "$JDK_NAME" ] && JDK_NAME="java-sdk"
    [ -z "$JDK_HOME" ] && JDK_HOME="/etc/alternatives/java_sdk"
    # Check required options are set

    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
CONFIG_FILE=
JDK_NAME=
JDK_HOME=


