#!/usr/bin/env bash
#
#/ command: jenkins:erase: "Erase the Jenkins packages from the system"
#
#/ usage: rerun jenkins:erase 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: jenkins:erase. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/erase/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/erase/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

sudo yum --quiet -y erase jenkins

if gpgKeyPackage=$(rpm -qa --queryformat '%{NAME}-%{VERSION}-%{SUMMARY}\n' gpg-pubkey* |grep 'Kohsuke Kawaguchi' |sed 's,-gpg(.*,,')
then
  sudo rpm -e "${gpgKeyPackage}"
fi

exit $?

# Done
