# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Nov 27 15:48:12 PST 2012
#
#/ usage: jenkins:cleanup [ --jenkins-home </var/lib/jenkins>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --jenkins-home) rerun_option_check $# ; JENKINS_HOME=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$JENKINS_HOME" ] && JENKINS_HOME="/var/lib/jenkins"
    # Check required options are set

    # If option variables are declared exportable, export them.
    export JENKINS_HOME
    #
    return 0
}


# Initialize the options variables to null.
JENKINS_HOME=


