#!/usr/bin/env bash
#
#/ command: jenkins:cleanup: "Remove Jenkins working files from the system."
#
#/ usage: rerun jenkins:cleanup [ --jenkins-home </var/lib/jenkins>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: JENKINS_HOME

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: jenkins:cleanup. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/cleanup/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/cleanup/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

sudo rm -rf ${JENKINS_HOME} /var/cache/jenkins /var/log/jenkins /etc/yum.repos.d/jenkins.repo.rpmsave

exit $?

# Done
