#!/usr/bin/env bash
#
#/ command: jenkins:remove: "remove the jenkins installation"
#
#/ usage: rerun jenkins:remove [ --cleanup <false>] 
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: CLEANUP

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/remove/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/remove/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: jenkins:remove. ***"' ERR
set -o nounset -o pipefail


# ------------------------------
# Your implementation goes here.
# ------------------------------

# Make sure Jenkins is stopped.
rerun jenkins:stop

# Erase the Jenkins packages from the system.
rerun jenkins:erase

# Cleanup the Jenkins working files, if required.
if [[ $CLEANUP = "true" ]]
then
  rerun jenkins:cleanup
fi

exit $?

# Done
