# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Wed Oct 31 10:15:52 PDT 2012
#
#/ usage: jenkins:update-job  --file|-f <>  --jobname|-j <> [ --url|-u <http://localhost:8080>] 

# print USAGE and exit
rerun_option_usage() {
    grep '^#/ usage:' <"$0" | cut -c4- >&2
    return 2
}

# print SYNTAX and exit
rerun_option_error() {
    if [[ "$RERUN_COLOR" == "true" ]]
    then echo >&2 -e """SYNTAX: $*"""
    else echo >&2 "SYNTAX: $*" 
    fi
    exit 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_usage
}

# options: [file jobname url]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        --file|-f) rerun_option_check $# ; FILE=$2 ; shift ;;
        --jobname|-j) rerun_option_check $# ; JOBNAME=$2 ; shift ;;
        --url|-u) rerun_option_check $# ; URL=$2 ; shift ;;
        # help option
        -?)
            rerun_option_usage
            exit 2
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$URL" ] && URL="http://localhost:8080"
# Check required options are set
[ -z "$FILE" ] && { echo >&2 "missing required option: --file" ; return 2 ; }
[ -z "$JOBNAME" ] && { echo >&2 "missing required option: --jobname" ; return 2 ; }
# If option variables are declared exportable, export them.

#
return 0
